### PR TITLE
Add providers

### PR DESCRIPTION
**Pull request by snovikov**

### CODE REVIEW

**Review by danvaida — APPROVED** [review]

**Review by danvaida — CHANGES_REQUESTED** [review]
See error in test case.

**Comment by snovikov** [comment]
@danvaida unfortunately I don't know how to mitigate this issue.

```
If you have feedback on the design of this feature, please open a GitHub issue
to discuss it.


Error: Module does not support depends_on

  on main.tf line 34, in module "example":
  34:   source = "../../"

Module "example" cannot be used with depends_on because it contains a nested
provider configuration for "github", at ../../providers.tf:1,10-18.
```

because removing `depend_on` will break apply

**Comment by danvaida** [comment]
https://www.terraform.io/language/modules/develop/providers Let's remove the provider initialisation from all modules :)

**Comment by snovikov** [comment]
Closing it, because it would be incompatible with `for_each`.

Ref: https://www.terraform.io/language/modules/develop/providers#providers-within-modules

**Pull request closed without merging**
